import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img />
          <a href='/'>Home</a>
          <a href='/events'>Events</a>
          <a href='/about-us'>About Us</a>
        </nav>
      </header>
      <main className={styles.main}>
        <a href=''>
        <img />
          <h2>Events in London</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut quis facilisis leo, eget porta leo. Quisque fermentum molestie quam, id ornare erat rhoncus pretium. Maecenas cursus urna non quam tristique, et accumsan nulla consequat. Donec arcu mauris, commodo eget nisi eu, pharetra luctus orci. Quisque sodales ex non orci mattis, quis rutrum ante pharetra. Pellentesque commodo sed nisi a facilisis. Nam dapibus efficitur dapibus. Pellentesque scelerisque rutrum tellus. Praesent velit leo, congue et ligula consectetur, viverra eleifend felis. Maecenas eu congue nisl, nec sollicitudin massa.</p>
        </a>
        <a href=''>
        <img />
          <h2>Events in New York City</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut quis facilisis leo, eget porta leo. Quisque fermentum molestie quam, id ornare erat rhoncus pretium. Maecenas cursus urna non quam tristique, et accumsan nulla consequat. Donec arcu mauris, commodo eget nisi eu, pharetra luctus orci. Quisque sodales ex non orci mattis, quis rutrum ante pharetra. Pellentesque commodo sed nisi a facilisis. Nam dapibus efficitur dapibus. Pellentesque scelerisque rutrum tellus. Praesent velit leo, congue et ligula consectetur, viverra eleifend felis. Maecenas eu congue nisl, nec sollicitudin massa.</p>
        </a>
        <a href=''>
        <img />
          <h2>Events in Paris</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut quis facilisis leo, eget porta leo. Quisque fermentum molestie quam, id ornare erat rhoncus pretium. Maecenas cursus urna non quam tristique, et accumsan nulla consequat. Donec arcu mauris, commodo eget nisi eu, pharetra luctus orci. Quisque sodales ex non orci mattis, quis rutrum ante pharetra. Pellentesque commodo sed nisi a facilisis. Nam dapibus efficitur dapibus. Pellentesque scelerisque rutrum tellus. Praesent velit leo, congue et ligula consectetur, viverra eleifend felis. Maecenas eu congue nisl, nec sollicitudin massa.</p>
        </a>
      </main>

      <footer className={styles.footer}>

      </footer>
    </>
  )
}
